---
name: Docker Image CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag bcgovimages/alpine-node-libreoffice:$(date +%s)
  docker-publish:
    needs: docker-build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event != 'pull_request' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: bcgovimages/alpine-node-libreoffice:latest
      - name: Inspect Docker Image
        run: docker image inspect bcgovimages/alpine-node-libreoffice:latest
